# In this config, you can tweak how certain commands function.
# Any changes to this config will require either a server restart, or `/seam reload`.
Feed-Fills-Saturation: true

Hat:
  # Items the player may not place on their head
  Blacklisted-Items:
    - "minecraft:barrier"
    - "minecraft:diamond_sword:1"
Repair:
  # Items the player may not repair.
  Blacklisted-Items:
    - "minecraft:wooden_axe"
    - "minecraft:wooden_axe:1"

# Do not touch this. This is solely for future config updates.
Config-Version: 1.0